services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    restart: unless-stopped

  bytewax:
    build:
      context: .
      dockerfile: docker/Dockerfile.bytewax
    depends_on:
      - redpanda
    environment:
      - KAFKA_BROKER=redpanda:9092
    volumes:
      - ./data:/app/data
    restart: always

  producer:
    build:
      context: .
      dockerfile: docker/Dockerfile.producer
    environment:
      - KAFKA_BROKER=redpanda:9092
      - KAFKA_TOPIC=orders-data
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: always