FROM python:3.11-slim
WORKDIR /app
COPY requirements.streamlit.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./app/streamlit_app.py .
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.enableCORS=false"]